name: Build and Deploy
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      pages: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate Mermaid Diagrams
        run: |
          npm i
          npm run build:mermaid

      - name: Deploy
        uses: jeswr/github-pages-blog-action@v0.1.1-alpha.2
        with:
          branch: gh-pages # Optional branch for GitHub Pages
          GITHUB_TOKEN: ${{ github.token }}
