name: Build and Deploy
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      pages: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: jeswr/github-pages-blog-action@v0.1.1-alpha.1
        with:
          branch: gh-pages # Optional branch for GitHub Pages
          GITHUB_TOKEN: ${{ github.token }}
